category_list = ['01. For Discussion','02. Recruiting','03. Supplier & Subcontractor Diversion','04. Inclusive Leadership Development','05. 2021 Strategic Planning: Improve Our Diversion Impact','06. Ideas/Brainstorm Items','07. Miscellaneous']
topics = ['Recruiting Update','Power BI Presentation','Industry Recruiting - EEO Data Collection','Field listening sessions/engagement follow up','D&I Manager follow up', '2021 Strategic Planning Follow Up','Department and Division Impact Reports','2021 Strategic Planning Follow Up','Field Listening Sessions','Book Study 2021', 'MWBE Outreach and Encompass Health','D&I Week 2021','New tracking software','Division Manger MWBE Partnerships and Outreach Best Practices Zoom Panel','Industry Recruiting - EEO Data Collection','American Bar Association "Diversion Brunch"', 'Web accessibility', 'Peer Support','Diversion & Preparation CONNECT Page','MWBE dollar spend tracking/improvements','Division Manger MWBE Partnerships and Outreach Best Practices','HBCU Recruiting Strategy','Field Diversion Strategy','Minority Employee Resource Group','Content of Senior Planning Team D&I presentation','Unconscious bias iLearning video','Jacksonville Culture Series','Consider revision to D&I mission statement','1st TSU co-op','2022 Planning','New committee members for 2022','Increasing Diversion In the Field','Campus Engagement Partners','EQUIP', 'Peer to Peer Initiative','MWBE Mentoring Initiative','Client Inquiries and Project Pursuit Support','Diversion Tracking/Accounting Improvements','Outreach Video','Diversion Tracking in Preconstruction','Trade Association Relationships','Marketing','Inclusive Leadership Conversation Series','Listening Sessions','Fall Book Study',
'D&I Newsletter Update',"JSA's Franklin Covey Unconscious Bias",'Construction Preparation Week','Adding D&I Core Competency in Performance Reviews','Grant/revolving loan fund development','Project Support','Inclusive Leadership Conversations','Employee listening session feedback','Unconscious bias iLearning video','D&I Book Study','2021 Strategic Planning','Web accessibility/accessibility','Candidate/interview tracking recommendation','Update on MWBE dollar spend tracking','Field Diversion strategy update','North Carolina A&T University (HBCU) partnership','HBCU summer internship feedback','HBCU panel with recruiters','Supplier/Subcontractor Impact Report','Grant/revolving loan fund development','Project Support','Candidate/interview tracking','2021 Strategic Planning','Employee listening session feedback','Future meetings and committee members','Assess demographics of field leadership','HICA board member support','Dollar spend tracking','Project Support','Unconscious bias iLearning video','Jacksonville Culture Series','Consider revision to D&I mission statement','Spirit Notes','July FTGU article']
topic_set = set(topics)
topic_list = list(topic_set)
total_combo_list = []
for category in category_list:
        for topic in topic_list:
                total_combo_list.append(category + " - " + topic)
for combo in total_combo_list:
        print(combo)



